### PR TITLE
enforce color use in tools

### PR DESCRIPTION
**Pull request by flying-sheep**
…as --color doesn’t propagate to scripts.

mocha needs an extra treatment due to ancient deps

### CODE REVIEW

**Comment by noseglid** [comment]
Cool. I'm happy to merge this if you fix the lint error described by travis:https://travis-ci.org/AtomBuild/atom-build-npm-apm/builds/105880546

**Comment by flying-sheep** [comment]
ah, whoops. too accustomed to semicolon-less style ¯\_(ツ)_/¯

**Comment by flying-sheep** [comment]
reopened because some curl call made the check fail unrelatedly

**Comment by noseglid** [comment]
Thanks for this!

**Pull request merged**
