### PR TITLE
add error matcher

### PR DESCRIPTION
**Pull request by pirfalt**
Error matcher for the times when you use npm scripts to start node
to run some js code.
The node stack trace with files, lines and columns is part of the
npm output if the process throws.

Example:
My testrun of pirfalt/hello-js@5c62bf96a346c0df6f57cc99eec5fed339453f2e

```
Executing: npm run run

> hello-js@1.0.0 run /Users/pirfalt/Dropbox/Code/hello-js
> node index.js

/Users/pirfalt/Dropbox/Code/hello-js/index.js:10
  throw new Error('bad')
  ^

Error: bad
    at three (/Users/pirfalt/Dropbox/Code/hello-js/index.js:10:9)
    at two (/Users/pirfalt/Dropbox/Code/hello-js/index.js:6:10)
    at one (/Users/pirfalt/Dropbox/Code/hello-js/index.js:2:10)
    at Object.<anonymous> (/Users/pirfalt/Dropbox/Code/hello-js/index.js:13:1)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Function.Module.runMain (module.js:447:10)
    at startup (node.js:141:18)

npm ERR! Darwin 15.3.0
npm ERR! argv "/usr/local/Cellar/node/5.7.0/bin/node" "/usr/local/bin/npm" "run" "run"
npm ERR! node v5.7.0
npm ERR! npm  v3.6.0
npm ERR! code ELIFECYCLE
npm ERR! hello-js@1.0.0 run: `node index.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the hello-js@1.0.0 run script 'node index.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the hello-js package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node index.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs hello-js
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls hello-js
npm ERR! There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/pirfalt/Dropbox/Code/hello-js/npm-debug.log
```

### CODE REVIEW

**Comment by noseglid** [comment]
So this is not really `npm`, but rather `node` output. I'm not sure this belongs here.

**Comment by pirfalt** [comment]
Yes. Its `node` output, and no i'm not sure if it fits here either.
But it's "just" an error matcher so nothing breaks. And it is useful.

Forking the project to call it "atom-build-node" with no other change also seems dumb.

**Comment by noseglid** [comment]
Sorry for dropping the ball on this one.
I agree with you. Error matcher doesn't hurt anything, and any number of errorMatchers can be appended for tools. Only problem would be if they conflict, but hey, if it matches then we at least have a match.

I'd be happy to merge this, but theres a merge conflict. Could you merge latest master into your branch?

**Comment by pirfalt** [comment]
I'll fix it on Monday, skiing now :)

**Pull request closed without merging**
